######################################################################
# Automatically generated by qmake (2.01a) czw. pa? 21 02:03:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
