######################################################################
# Automatically generated by qmake (2.01a) czw. pa? 21 05:30:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h
SOURCES += imageviewer.cpp main.cpp
